name: Ansible Lint and Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible:
    name: Ansible Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ansible and ansible-lint
      run: |
        sudo apt update
        sudo apt install -y ansible
        pip install ansible-lint
    
    - name: Run Ansible playbook
      run: ansible-playbook playbook.yml --check -i inventory.ini
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        ANSIBLE_SSH_PRIVATE_KEY_FILE: /tmp/ssh_key
      shell: bash

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/my-key.pem
        chmod 600 ~/.ssh/my-key.pem
        ssh-keyscan -H 44.223.80.103 >> ~/.ssh/known_hosts
    
    - name: Run ansible-lint
      run: ansible-lint playbook.yml

    - name: Run Ansible syntax check
      run: ansible-playbook playbook.yml --syntax-check -i inventory.ini

    - name: Run Ansible dry-run (check mode)
      run: |
        ansible-playbook playbook.yml --check -i inventory.ini
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
