name: Ansible Lint and Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ansible:
    name: Ansible Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible and ansible-lint
        run: |
          sudo apt update
          sudo apt install -y ansible
          pip install ansible-lint
      - name: Setup SSH Environment
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

        # Test connection
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_IP }} "echo SSH connection successful!"
      - name: Run ansible-lint
        run: ansible-lint playbook.yml
      - name: Run Ansible syntax check
        run: ansible-playbook playbook.yml --syntax-check -i inventory.ini
      - name: Run Ansible dry-run (check mode)
        run: ansible-playbook playbook.yml --check -i inventory.ini
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_SSH_PRIVATE_KEY_FILE: ~/.ssh/id_rsa
