name: Terraform Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Init & Validate
    runs-on: ubuntu-latest
    environment: production  # Optional: use GitHub environments for secrets

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6
        terraform_wrapper: false  # Disable wrapper for cleaner output

    - name: Terraform Init
      run: terraform init -input=false
      env:
        TF_INPUT: "false"  # Never prompt for input

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -input=false -no-color -detailed-exitcode
      env:
        TF_CLI_ARGS: "-no-color"
      continue-on-error: true  # Allows workflow to continue on plan differences

    - name: Upload Plan Artifact
      if: always()  # Upload even if previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: |
          *.tfplan
          plan.out
